import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { coreColors, extendedColors, semanticColors } from '../../src/tokens/colors.js';
import { spacingScale } from '../../src/tokens/spacing.js';
import { radiiScale } from '../../src/tokens/radii.js';
import { lineHeights, letterSpacings } from '../../src/tokens/typography.js';
import { parseColorToFigma } from './color-parser.js';
import type { FigmaColor } from './types.js';

// ---------------------------------------------------------------------------
// Types for the plugin-friendly payload
// ---------------------------------------------------------------------------
interface PluginVariable {
  name: string;
  type: 'COLOR' | 'FLOAT';
  description: string;
  values: Record<string, FigmaColor | number>;
}

interface PluginCollection {
  name: string;
  modes: string[];
  variables: PluginVariable[];
}

interface PluginTokenData {
  collections: PluginCollection[];
  meta: { generatedAt: string; totalVariables: number; totalCollections: number };
}

// ---------------------------------------------------------------------------
// Helpers (same logic as build-payload.ts)
// ---------------------------------------------------------------------------
function stripPrefix(variable: string): string {
  return variable.replace(/^--/, '');
}

function parsePixelValue(value: string): number {
  if (value === '0') return 0;
  const match = value.match(/^([\d.]+)px$/);
  if (!match) throw new Error(`Cannot parse pixel value: "${value}"`);
  return parseFloat(match[1]);
}

function parseEmValue(value: string): number {
  if (value === '0') return 0;
  const match = value.match(/^(-?[\d.]+)em$/);
  if (!match) throw new Error(`Cannot parse em value: "${value}"`);
  return parseFloat(match[1]);
}

// ---------------------------------------------------------------------------
// Build the plugin-friendly token data
// ---------------------------------------------------------------------------
function buildTokenData(): PluginTokenData {
  const collections: PluginCollection[] = [];

  // Colors — Light/Dark modes
  const allColors = [
    ...coreColors.map(c => ({ ...c, group: 'core' })),
    ...extendedColors.map(c => ({ ...c, group: 'extended' })),
    ...semanticColors.map(c => ({ ...c, group: 'semantic' })),
  ];
  collections.push({
    name: 'Colors',
    modes: ['Light', 'Dark'],
    variables: allColors.map(color => ({
      name: `${color.group}/${stripPrefix(color.variable)}`,
      type: 'COLOR' as const,
      description: `${color.description} — ${color.usage}`,
      values: {
        Light: parseColorToFigma(color.light),
        Dark: parseColorToFigma(color.dark),
      },
    })),
  });

  // Spacing — single mode
  collections.push({
    name: 'Spacing',
    modes: ['Default'],
    variables: spacingScale.map(token => ({
      name: stripPrefix(token.variable),
      type: 'FLOAT' as const,
      description: token.description,
      values: { Default: token.px },
    })),
  });

  // Radii — single mode, skip percentage values
  const supportedRadii = radiiScale.filter(t => !t.value.includes('%'));
  collections.push({
    name: 'Radii',
    modes: ['Default'],
    variables: supportedRadii.map(token => ({
      name: stripPrefix(token.variable),
      type: 'FLOAT' as const,
      description: `${token.description} — ${token.usage}`,
      values: { Default: parsePixelValue(token.value) },
    })),
  });

  // Typography — line-heights + letter-spacings
  collections.push({
    name: 'Typography',
    modes: ['Default'],
    variables: [
      ...lineHeights.map(token => ({
        name: `line-height/${stripPrefix(token.variable).replace('leading-', '')}`,
        type: 'FLOAT' as const,
        description: token.description,
        values: { Default: parseFloat(token.value) },
      })),
      ...letterSpacings.map(token => ({
        name: `letter-spacing/${stripPrefix(token.variable).replace('tracking-', '')}`,
        type: 'FLOAT' as const,
        description: `${token.description} (value in em)`,
        values: { Default: parseEmValue(token.value) },
      })),
    ],
  });

  const totalVariables = collections.reduce((sum, c) => sum + c.variables.length, 0);
  return {
    collections,
    meta: {
      generatedAt: new Date().toISOString(),
      totalVariables,
      totalCollections: collections.length,
    },
  };
}

// ---------------------------------------------------------------------------
// Generate the self-contained plugin code.js
// ---------------------------------------------------------------------------
function generatePluginCode(data: PluginTokenData): string {
  return `// Auto-generated by scripts/figma/build-plugin.ts
// Generated: ${data.meta.generatedAt}
// Do not edit manually. Run: npm run figma:build-plugin

var TOKEN_DATA = ${JSON.stringify(data, null, 2)};

figma.showUI(__html__, { width: 320, height: 420 });

figma.ui.onmessage = function(msg) {
  if (msg.type !== 'import') return;

  try {
    // Check for existing collections with the same names
    var existing = figma.variables.getLocalVariableCollections();
    var existingNames = existing.map(function(c) { return c.name; });
    var conflicts = TOKEN_DATA.collections.filter(function(c) {
      return existingNames.indexOf(c.name) !== -1;
    });
    if (conflicts.length > 0) {
      figma.ui.postMessage({
        type: 'warning',
        text: 'Collections already exist: ' + conflicts.map(function(c) { return c.name; }).join(', ') +
          '. New duplicates will be created. Delete old ones manually if needed.'
      });
    }

    var totalCreated = 0;

    for (var ci = 0; ci < TOKEN_DATA.collections.length; ci++) {
      var col = TOKEN_DATA.collections[ci];
      figma.ui.postMessage({ type: 'progress', text: 'Creating ' + col.name + ' collection...' });
      figma.ui.postMessage({ type: 'log', text: col.name + ':' });

      // Create collection
      var collection = figma.variables.createVariableCollection(col.name);

      // Rename the auto-created default mode
      var defaultModeId = collection.modes[0].modeId;
      collection.renameMode(defaultModeId, col.modes[0]);

      // Build mode map
      var modeIds = {};
      modeIds[col.modes[0]] = defaultModeId;

      // Try to add additional modes (fails on free plan for > 1 mode)
      for (var mi = 1; mi < col.modes.length; mi++) {
        try {
          var newModeId = collection.addMode(col.modes[mi]);
          modeIds[col.modes[mi]] = newModeId;
          figma.ui.postMessage({ type: 'log', text: '  + Mode: ' + col.modes[mi] });
        } catch (e) {
          figma.ui.postMessage({
            type: 'warning',
            text: 'Could not add "' + col.modes[mi] + '" mode to ' + col.name + '. ' +
              'Your Figma plan limits this collection to ' + collection.modes.length + ' mode(s). ' +
              'Upgrade to Professional for Light/Dark modes. Importing ' + col.modes[0] + ' values only.'
          });
          figma.ui.postMessage({ type: 'log', text: '  ! Mode limit: ' + col.modes[mi] + ' skipped' });
        }
      }

      // Create variables
      for (var vi = 0; vi < col.variables.length; vi++) {
        var v = col.variables[vi];
        var variable = figma.variables.createVariable(v.name, collection, v.type);
        if (v.description) variable.description = v.description;

        var modeNames = Object.keys(modeIds);
        for (var ki = 0; ki < modeNames.length; ki++) {
          var modeName = modeNames[ki];
          if (v.values[modeName] !== undefined) {
            variable.setValueForMode(modeIds[modeName], v.values[modeName]);
          }
        }

        totalCreated++;
        figma.ui.postMessage({ type: 'log', text: '  ' + v.name });
      }

      figma.ui.postMessage({ type: 'log', text: '' });
    }

    figma.ui.postMessage({
      type: 'progress',
      text: 'Done! Created ' + totalCreated + ' variables across ' + TOKEN_DATA.collections.length + ' collections.'
    });
    figma.ui.postMessage({ type: 'done' });
    figma.notify('Imported ' + totalCreated + ' design token variables.');
  } catch (err) {
    var errMsg = err && err.message ? err.message : String(err);
    figma.ui.postMessage({ type: 'error', text: 'Error: ' + errMsg });
    figma.ui.postMessage({ type: 'done' });
  }
};
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '../../figma-plugin/code.js');

const data = buildTokenData();
const code = generatePluginCode(data);
writeFileSync(outputPath, code, 'utf-8');

console.log('Figma plugin built successfully!\n');
console.log(`  Collections: ${data.meta.totalCollections}`);
console.log(`  Variables:   ${data.meta.totalVariables}`);
console.log(`  Output:      figma-plugin/code.js`);
